### ISSUE TITLE
metacat dataset show hms:test  

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#12]
<schellma> metacat dataset show hms:test
Traceback (most recent call last):
  File "/nashome/s/schellma/.local/bin/metacat", line 33, in <module>
    sys.exit(load_entry_point('metacat==3.15.8', 'console_scripts', 'metacat')())
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/ui/metacat_ui.py", line 91, in main
    cli.run(sys.argv, argv0="metacat")
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/ui/cli/cli.py", line 216, in run
    self._run(command, context, argv, usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/ui/cli/cli.py", line 211, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/ui/cli/cli.py", line 211, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/ui/cli/cli.py", line 112, in _run
    return self(command, context, opts, args)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/ui/metacat_dataset.py", line 139, in __call__
    info = client.get_dataset(args[0])
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.15.8-py3.9.egg/metacat/webapi/webapi.py", line 255, in get_dataset
    return self.get_json(f"data/dataset?dataset={spec}")
UnboundLocalError: local variable 'spec' referenced before assignment

**Comment by hschellman** [comment]
HI, found the solution on this.  Just need to set spec=did before you check on namespace==None on line 252 of webapi.py
