### ISSUE TITLE
metacat dataset show command ? 

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#14]
I'd like to check the metadata for my dataset.  I can update but not show:

metacat dataset show schellma:protodune-sp-physics-generic

gives the old: 

Traceback (most recent call last):
  File "/Users/schellma/.local/bin/metacat", line 33, in <module>
    sys.exit(load_entry_point('metacat==3.15.10', 'console_scripts', 'metacat')())
  File "/Users/schellma/metacat/metacat/ui/metacat_ui.py", line 91, in main
    cli.run(sys.argv, argv0="metacat")
  File "/Users/schellma/metacat/metacat/ui/cli/cli.py", line 216, in run
    self._run(command, context, argv, usage_on_error)
  File "/Users/schellma/metacat/metacat/ui/cli/cli.py", line 211, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/Users/schellma/metacat/metacat/ui/cli/cli.py", line 211, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/Users/schellma/metacat/metacat/ui/cli/cli.py", line 112, in _run
    return self(command, context, opts, args)
  File "/Users/schellma/metacat/metacat/ui/metacat_dataset.py", line 139, in __call__
    info = client.get_dataset(args[0])
  File "/Users/schellma/metacat/metacat/webapi/webapi.py", line 257, in get_dataset
    return self.get_json(f"data/dataset?dataset={spec}")
UnboundLocalError: local variable 'spec' referenced before assignment

needs to set spec=did if namespace == none but does not.

**Comment by hschellman** [comment]
Duplicate, closing this one
