### ISSUE TITLE
can't make dataset from query

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#20]
I;'m trying to make a dataset from a query and it fails if I try to make directly or add suing the -q command. 

The older make a list and add that seems to work

 metacat version
MetaCat Server URL:         https://metacat.fnal.gov:9443/dune_meta_demo/app
Authentication server URL:  https://metacat.fnal.gov:8143/auth/dune
Server version:             3.22.0
Client version:             3.22.2

metacat dataset create -f "files from schellma:protodune-sp-physics-generic where core.runs[any] in (5141,5413)"  schellma:runs5141to5143 "recent files"
<html><body><h2>Application error</h2>
            <h3>run() got an unexpected keyword argument 'default_namespace'</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 715, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 485, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 483, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 253, in create_dataset
    files = query.run(db, filters=self.App.filters(), with_meta=False, with_provenance=False, default_namespace=namespace or None)
TypeError: run() got an unexpected keyword argument 'default_namespace'
</pre>
            </body>
            </html>

I then created an empty dataset  schellma:runs5141to5143 but now I can't add to it.

 metacat dataset add-files -q"files from schellma:protodune-sp-physics-generic where core.runs[any] in (5141,5413)"  schellma:runs5141to5143
<html><body><h2>Application error</h2>
            <h3>name 'namespace' is not defined</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 715, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 485, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 483, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 389, in add_files
    files = query.run(db, filters=self.App.filters(), with_meta=False, with_provenance=False, default_namespace=namespace or None)
NameError: name 'namespace' is not defined
</pre>
            </body>
            </html>

metacat dataset add-files -i @physics_ids.txt schellma:runs5141to5143   worked

**Comment by ivmfnal** [comment]
Fixed
