### ISSUE TITLE
metacat query --summary fails where the normal query gives a nice list

### ISSUE THREAD

**Issue by hschellman** [ivmfnal/metacat#22]
I'm having trouble with the summary option.  I think there needs to be a list around a generator here. 

metacat version
MetaCat Server URL:         https://metacat.fnal.gov:9443/dune_meta_demo/app
Authentication server URL:  https://metacat.fnal.gov:8143/auth/dune
Server version:             3.24.0
Client version:             3.24.1

 metacat query --summary "files from dune:all where core.run_type=protodune-sp and core.data_tier=full-reconstructed and core.data_stream=physics and DUNE.campaign=PDSPProd4 and core.first_event_number=1 "
Traceback (most recent call last):
  File "/nashome/s/schellma/.local/bin/metacat", line 33, in <module>
    sys.exit(load_entry_point('metacat==3.24.1', 'console_scripts', 'metacat')())
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.24.1-py3.9.egg/metacat/ui/metacat_ui.py", line 167, in main
    cli.run(sys.argv, argv0="metacat")
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.24.1-py3.9.egg/metacat/ui/cli/cli.py", line 216, in run
    self._run(command, context, argv, usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.24.1-py3.9.egg/metacat/ui/cli/cli.py", line 211, in _run
    return interp._run(pre_command + word, context, rest, usage_on_error = usage_on_error)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.24.1-py3.9.egg/metacat/ui/cli/cli.py", line 112, in _run
    return self(command, context, opts, args)
  File "/nashome/s/schellma/.local/lib/python3.9/site-packages/metacat-3.24.1-py3.9.egg/metacat/ui/metacat_query.py", line 117, in __call__
    print("%d files" % (len(results),))
TypeError: object of type 'generator' has no len()

**Comment by ivmfnal** [comment]
closed by mistake

**Comment by ivmfnal** [comment]
Fixed, please upgrade to version 3.24.3
