### ISSUE TITLE
Can't show metadata categories

### ISSUE THREAD

**Issue by calcuttj** [ivmfnal/metacat#40]
Attempting to explore what metadata can be queried against. Getting errors when trying to see the metadata categories

```workflow$ metacat category show DUNE_MC
<html><body><h2>Application error</h2>
            <h3>object of type 'NoneType' has no len()</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 1475, in category
    cat = DBParamCategory.get(db, path)
  File "./metacat_server_dune/lib/metacat/common/dbbase.py", line 82, in get
    assert len(pkvalues) == len(cls.PK)
TypeError: object of type 'NoneType' has no len()
</pre>
            </body>
            </html>
workflow$ metacat category show DUNE
<html><body><h2>Application error</h2>
            <h3>object of type 'NoneType' has no len()</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 1475, in category
    cat = DBParamCategory.get(db, path)
  File "./metacat_server_dune/lib/metacat/common/dbbase.py", line 82, in get
    assert len(pkvalues) == len(cls.PK)
TypeError: object of type 'NoneType' has no len()
</pre>
            </body>
            </html>
workflow$ metacat category show core
<html><body><h2>Application error</h2>
            <h3>object of type 'NoneType' has no len()</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 1475, in category
    cat = DBParamCategory.get(db, path)
  File "./metacat_server_dune/lib/metacat/common/dbbase.py", line 82, in get
    assert len(pkvalues) == len(cls.PK)
TypeError: object of type 'NoneType' has no len()
</pre>
            </body>
            </html>
```

**Comment by ahiguera-mx** [comment]
I have encountered a similar issue. Here is a minimal example 
`$ metacat category list
$ metacat category show dune_mc

<html><body><h2>Application error</h2>
            <h3>object of type 'NoneType' has no len()</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 1475, in category
    cat = DBParamCategory.get(db, path)
  File "./metacat_server_dune/lib/metacat/common/dbbase.py", line 82, in get
    assert len(pkvalues) == len(cls.PK)
TypeError: object of type 'NoneType' has no len()
</pre>
            </body>
            </html>`


MetaCat Server URL:     https://metacat.fnal.gov:9443/dune_meta_demo/app
Authentication server URL: https://metacat.fnal.gov:8143/auth/dune
Server version:       3.42.0
Client version:       3.36.1

**Comment by ivmfnal** [comment]
Fixed that.
