### ISSUE TITLE
update-metadata command fails

### ISSUE THREAD

**Issue by rlcee** [ivmfnal/metacat#41]
In  metacat-3.42.0

> metacat file update-meta -f rlc:etc.rlc.dh_test.000.000.txt '{ "mm.testb" : true, "mm.tests" : ["seqa"] }'

<html><body><h2>Application error</h2>
            <h3>update_many() got an unexpected keyword argument 'do_commit'</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_generic/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_generic/server/data_handler.py", line 1185, in update_file_meta
    return self.__update_meta_bulk(db, user, data["metadata"], data["mode"], ids=by_fid, names=by_namespace_name)
  File "./metacat_server_generic/server/data_handler.py", line 1005, in __update_meta_bulk
    DBFile.update_many(db, file_set, do_commit=True)
  File "./metacat_server_generic/lib/metacat/common/dbbase.py", line 18, in decorated
    return method(first, *params, transaction=transaction, **args)
TypeError: update_many() got an unexpected keyword argument 'do_commit'
</pre>
            </body>
            </html>

**Comment by marcmengel** [comment]
Tracking this over in [marcmengel's fork](https://github.com/marcmengel/metacat/issues/1)
